[project]
name = 'stacks_audiobits'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stacks_audiobits]
path = 'contracts/stacks_audiobits.clar'
clarity_version = 1
epoch = '2.0'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
